version: '3'
services:
  tests:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    stdin_open: true
    volumes:
      - /usr/app/node_modules
      - .:/usr/app
    command: ['npm', 'run', 'test']
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    stdin_open: true
    ports:
      - '3000:3000'
    volumes:
      - /usr/app/node_modules
      - .:/usr/app